name       : haskell-profunctors
version    : 5.2
release    : 1
source     :
    - http://hackage.haskell.org/package/profunctors-5.2/profunctors-5.2.tar.gz : 87a7e25c4745ea8ff479dd1212ec2e57710abb3d3dd30f948fa16be1d3ee05a4
license    : BSD-3-Clause
component  : programming.haskell
summary    : Profunctors
description: |
    Profunctors
builddeps  :
    - haskell-bifunctors
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
