name       : haskell-profunctors
version    : 5.5.2
release    : 4
source     :
    - https://hackage.haskell.org/package/profunctors-5.5.2/profunctors-5.5.2.tar.gz : 5f1579aab8afae377c7c7c0d0ed95b0bc58003b6dad2d494045f7472a398af7c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Profunctors
description: |
    Profunctors
builddeps  :
    - haskell-bifunctors-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-bifunctors-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
