name       : haskell-profunctors
version    : 5.2.2
release    : 3
source     :
    - https://hackage.haskell.org/package/profunctors-5.2.2/profunctors-5.2.2.tar.gz : e981e6a33ac99d38a947a749179bbea3c294ecf6bfde41660fe6d8d5a2e43768
license    : BSD-3-Clause
component  : programming.haskell
summary    : Profunctors
description: |
    Profunctors
builddeps  :
    - haskell-base-orphans
    - haskell-bifunctors
    - haskell-cabal-install
    - haskell-comonad
    - haskell-distributive
setup      : |
    sed -i "s|0.7|0.8|g" profunctors.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
